import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// Global CSS
import "./styles/globals.css";
import SideNavigation from "@/components/common/navigation/SideNavigation";

const roboto = Roboto({ subsets: ["latin"], weight: ["400","500", "700"] });

export const metadata: Metadata = {
  title: "Shadcn UI - todo board",
  description: "Generated by create next app with Shadcn UI & Supabase",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SideNavigation />
        {children}</body>
    </html>
  );
}
